__version__      = '0.1'
__copyright__    = 'Copyright 2019, Simon Olofsson and Eduardo Schultz'
__author__       = 'Simon Olofsson and Eduardo Schultz'
__author_email__ = 'simon.olofsson15@imperial.ac.uk'
__license__      = 'MIT License'